spring:
#  profiles:
#      active: prod
  thymeleaf:
     prefix: classpath:/views/
  server:
      port: 80
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: zfj1121
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true

